### ISSUE TITLE
加载插件失败

### ISSUE THREAD

**Issue by devopana** [Yanyutin753/wechat_pictureChange#1]
[WARNING][2023-09-06 20:43:57][plugin_manager.py:113] - Failed to import plugin pictureChange: No module named 'plugins.pictureChange.sdwebui'

**Comment by Yanyutin753** [comment]
你现在看看，我改了点数据

**Comment by devopana** [comment]
> 你现在看看，我改了点数据

更新之后好像还是依赖sdwebui：
Traceback (most recent call last):
  File "/home/ubuntu/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 35, in handler_single_msg
    WechatChannel().handle_single(cmsg)
  File "/home/ubuntu/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 64, in wrapper
    return func(self, cmsg)
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 157, in handle_single
    context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=False, msg=cmsg)
  File "/home/ubuntu/chatgpt-on-wechat/channel/chat_channel.py", line 44, in _compose_context
    with open(config_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/chatgpt-on-wechat/channel/../plugins/sdwebui/config.json'

然后装了sdwebui插件之后又报错：
Traceback (most recent call last):
  File "/home/ubuntu/chatgpt-on-wechat/lib/itchat/components/register.py", line 63, in configured_reply
    r = replyFn(msg)
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 35, in handler_single_msg
    WechatChannel().handle_single(cmsg)
  File "/home/ubuntu/chatgpt-on-wechat/common/time_check.py", line 40, in _time_checker
    f(self, *args, **kwargs)  # 未开启时间模块则直接回答
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 64, in wrapper
    return func(self, cmsg)
  File "/home/ubuntu/chatgpt-on-wechat/channel/wechat/wechat_channel.py", line 157, in handle_single
    context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=False, msg=cmsg)
  File "/home/ubuntu/chatgpt-on-wechat/channel/chat_channel.py", line 46, in _compose_context
    use_group = config_Sd["use_group"]
KeyError: 'use_group'

**Comment by Yanyutin753** [comment]
你的插件文件夹改成pictureChange没，然后改godcmd,然后启动插件

**Comment by Yanyutin753** [comment]
![image](https://github.com/Yanyutin753/wechat_pictureChange/assets/132346501/2d78d7a4-a1b3-466f-a3cf-10a147c43109)
![image](https://github.com/Yanyutin753/wechat_pictureChange/assets/132346501/4527a655-926f-4f96-aac9-d0defc9ffb53)

**Comment by Yanyutin753** [comment]
个人号是要改chat_channel的

**Comment by Yanyutin753** [comment]
context = self._compose_context(cmsg.ctype, cmsg.content, isgroup=False, msg=cmsg) File "/home/ubuntu/chatgpt-on-wechat/channel/chat_channel.py", line 46, in _compose_context use_group = config_Sd["use_group"] KeyError: 'use_group'你这里应该就是没改文件，我现在这个代码只支持python3部署

**Comment by devopana** [comment]
改了新的chat_channel和godcmd不报错了，但是发送图片没有反应，文生图还是走的openai，但是确认插件已经注册且加载
![image](https://github.com/Yanyutin753/wechat_pictureChange/assets/94607574/921f0e7b-73fd-4390-9bfb-c39ac13e27b0)

**Comment by Yanyutin753** [comment]
你启动了吗，插件要启动才能用，文生图不能用，说明没启动，正常来说我的没启动，文生图就会是openai,要是启动了，就不会是openai,出现错误就报错

**Comment by devopana** [comment]
确实是我没启动，不好意思，问题解决了

**Comment by mashagua** [comment]
这里你的百度云api_key是怎么申请？百度的api很多，选择哪个接口创建对应的api_key和secret

**Comment by Yanyutin753** [comment]
@mashagua https://ai.baidu.com/tech/imageprocess/enhancement
